### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by NoerGitKat** [digitalfabrik/lunes-app#1]
# Splash Screen

This is the first screen a user sees when they open the application.

**DESIGN**: [Zeplin](https://zpl.io/2vv7R8Y)

## User Story

- As a learner, I can view the app introduction once I open the app for the first time after installation.

## Acceptance Criteria

- [x] Shows Lunes Logo in the center of screen
- [x] Shows 6 icons in various places according to design
- [x] Displays screen for 3-5 seconds
- [x] Redirects to Profession Selection screen

**Comment by DaveOuds** [comment]
Working for android, but missing IOS implementation.
