### ISSUE TITLE
Update Android Target API

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/lunes-app#1029]
**Is your feature request related to a problem? Please describe.**
Google requirement: Deadline August 31 2024

- New apps and app updates must target Android 14 (API level 34) to be submitted to Google Play

- Existing apps must target Android 13 (API level 33) or higher to remain available to new users on devices running Android OS higher than your app’s target API level. Apps that target Android 12 (API level 31) or lower ( Android 10 or lower for Wear OS and Android 11 or lower for TV OS), will only be available on devices running Android OS that are the same or lower than your apps’ target API level.

See more here:
https://support.google.com/googleplay/android-developer/answer/11926878?hl=en#:~:text=Starting%20August%2031%202024%3A,target%20Android%2013%20or%20higher).

**Comment by steffenkleinle** [comment]
Will be done in #1010.

**Comment by ztefanie** [comment]
@f1sh1918 create a draft PR already here: https://github.com/digitalfabrik/lunes-app/pull/1030

**Comment by steffenkleinle** [comment]
> @f1sh1918 create a draft PR already here: #1030

I know, but it seems like react-native needs to be upgraded to make this work :see_no_evil:

**Comment by ztefanie** [comment]
closed in favor of https://github.com/digitalfabrik/lunes-app/issues/1010
