### ISSUE TITLE
Update Android Version

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/lunes-app#955]
**Is your feature request related to a problem? Please describe.**
Google won't let us update our App in the Play Store after 31 August if we haven't updated to Android 13 (API 33) by then.

**Describe the solution you'd like**
Update to API 33.

**Describe alternatives you've considered**
Let's not.

**Additional context**
https://play.google.com/console/developers/5269030016285360668/app/4973131027931283146/policy-center

**Comment by sarahsporck** [comment]
Aparrently our target sdk is already is 33. To test this run `apkanalyzer manifest target-sdk` and check out our build.gradle. When checking for `affected bundles` in the google play console, there is only one result of an uploaded app for internal testing in 2021. Maybe we need to remove this one? @SteffiStuffel

**Comment by sarahsporck** [comment]
https://stackoverflow.com/questions/76931031/warning-app-must-target-android-13-api-level-33-or-higher-it-does it seems the solution is to just create a new release on the track. 👍🏼
