### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/lunes-app#983]
**Is your feature request related to a problem? Please describe.**
It is about time we upgrade our dependencies again. 

**Describe the solution you'd like**
Update all dependencies that only need a reasonable amount of work and create issues for upgrading other dependencies.

Issues for separate upgrades:
- react-native: #1010
- victory-native: #1011
- react-native-audio-record-player: #890

**Describe alternatives you've considered**
Not updating.

**Additional context**
Checkout https://github.com/digitalfabrik/integreat-app/issues/2290 if there are problems. They might be resolved there

**Comment by sarahsporck** [comment]
I realized that I didn't work on this ticket for more than a month and honestly also feel like I don't have the capacity to do this. I think the major blocker was react-native-camera. Therefore, I'll unassign myself.

**Comment by steffenkleinle** [comment]
react-native-camera is deprecated/archived and react-native-vision-camera is recommended instead.
