### ISSUE TITLE
[XCode 15] hash.hpp error for RCT.Folly

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/lunes-app#999]
### Describe the Bug

Can not build app with XCode 15 on react-native 0.70.x

### Steps to Reproduce

1. Build app with XCode 15
2. Check hash.hpp error for RCT.Folly

### Expected Behavior

XCode can build app

### Actual Behavior

Xcode fails on build

### Additional Information

https://github.com/facebook/react-native/issues/37748

**Comment by LeandraH** [comment]
Not an issue in 15.0.1 anymore
